[package]
name = "bip44"
version = "0.1.0"
edition = "2021"
authors = ["Liam"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.4"
eyre = "0.6.8"
tokio = { version = "1", features = ["full"] }
